function(collect_include_directories TARGET VAR)
    if (NOT TARGET ${TARGET})
        message(FATAL_ERROR "'${TARGET}' is not a valid target.")
        return()
    endif ()
    get_target_property(TGT_DIRS ${TARGET} INTERFACE_INCLUDE_DIRECTORIES)
    get_target_property(TGT_LIBS ${TARGET} INTERFACE_LINK_LIBRARIES)
    if (NOT TGT_LIBS STREQUAL "TGT_LIBS-NOTFOUND")
        foreach (LIB ${TGT_LIBS})
            if (NOT TARGET ${LIB})
                message(FATAL_ERROR "'${LIB}' is not a valid library. (Used by ${TARGET})")
            endif ()
            collect_include_directories(${LIB} LIB_DIRS)
            if (NOT LIB_DIRS STREQUAL "")
                list(APPEND TGT_DIRS ${LIB_DIRS})
            endif ()
        endforeach ()
    endif ()
    set(${VAR} ${TGT_DIRS} PARENT_SCOPE)
endfunction()